/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.payment;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PaymentCreatedValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 727698570799786289L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentCreatedValue\",\"namespace\":\"com.example.payment\",\"fields\":[{\"name\":\"request_id\",\"type\":\"string\"},{\"name\":\"payment_id\",\"type\":\"long\"},{\"name\":\"type\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentCreatedValue> ENCODER =
      new BinaryMessageEncoder<PaymentCreatedValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentCreatedValue> DECODER =
      new BinaryMessageDecoder<PaymentCreatedValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PaymentCreatedValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PaymentCreatedValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PaymentCreatedValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PaymentCreatedValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PaymentCreatedValue from a ByteBuffer. */
  public static PaymentCreatedValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence request_id;
  @Deprecated public long payment_id;
  @Deprecated public java.lang.CharSequence type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentCreatedValue() {}

  /**
   * All-args constructor.
   * @param request_id The new value for request_id
   * @param payment_id The new value for payment_id
   * @param type The new value for type
   */
  public PaymentCreatedValue(java.lang.CharSequence request_id, java.lang.Long payment_id, java.lang.CharSequence type) {
    this.request_id = request_id;
    this.payment_id = payment_id;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return request_id;
    case 1: return payment_id;
    case 2: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: request_id = (java.lang.CharSequence)value$; break;
    case 1: payment_id = (java.lang.Long)value$; break;
    case 2: type = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'request_id' field.
   * @return The value of the 'request_id' field.
   */
  public java.lang.CharSequence getRequestId() {
    return request_id;
  }

  /**
   * Sets the value of the 'request_id' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.CharSequence value) {
    this.request_id = value;
  }

  /**
   * Gets the value of the 'payment_id' field.
   * @return The value of the 'payment_id' field.
   */
  public java.lang.Long getPaymentId() {
    return payment_id;
  }

  /**
   * Sets the value of the 'payment_id' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.Long value) {
    this.payment_id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Creates a new PaymentCreatedValue RecordBuilder.
   * @return A new PaymentCreatedValue RecordBuilder
   */
  public static com.example.payment.PaymentCreatedValue.Builder newBuilder() {
    return new com.example.payment.PaymentCreatedValue.Builder();
  }

  /**
   * Creates a new PaymentCreatedValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentCreatedValue RecordBuilder
   */
  public static com.example.payment.PaymentCreatedValue.Builder newBuilder(com.example.payment.PaymentCreatedValue.Builder other) {
    return new com.example.payment.PaymentCreatedValue.Builder(other);
  }

  /**
   * Creates a new PaymentCreatedValue RecordBuilder by copying an existing PaymentCreatedValue instance.
   * @param other The existing instance to copy.
   * @return A new PaymentCreatedValue RecordBuilder
   */
  public static com.example.payment.PaymentCreatedValue.Builder newBuilder(com.example.payment.PaymentCreatedValue other) {
    return new com.example.payment.PaymentCreatedValue.Builder(other);
  }

  /**
   * RecordBuilder for PaymentCreatedValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentCreatedValue>
    implements org.apache.avro.data.RecordBuilder<PaymentCreatedValue> {

    private java.lang.CharSequence request_id;
    private long payment_id;
    private java.lang.CharSequence type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.payment.PaymentCreatedValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.request_id)) {
        this.request_id = data().deepCopy(fields()[0].schema(), other.request_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.payment_id)) {
        this.payment_id = data().deepCopy(fields()[1].schema(), other.payment_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentCreatedValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.payment.PaymentCreatedValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.request_id)) {
        this.request_id = data().deepCopy(fields()[0].schema(), other.request_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.payment_id)) {
        this.payment_id = data().deepCopy(fields()[1].schema(), other.payment_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'request_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getRequestId() {
      return request_id;
    }

    /**
      * Sets the value of the 'request_id' field.
      * @param value The value of 'request_id'.
      * @return This builder.
      */
    public com.example.payment.PaymentCreatedValue.Builder setRequestId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.request_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'request_id' field has been set.
      * @return True if the 'request_id' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'request_id' field.
      * @return This builder.
      */
    public com.example.payment.PaymentCreatedValue.Builder clearRequestId() {
      request_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_id' field.
      * @return The value.
      */
    public java.lang.Long getPaymentId() {
      return payment_id;
    }

    /**
      * Sets the value of the 'payment_id' field.
      * @param value The value of 'payment_id'.
      * @return This builder.
      */
    public com.example.payment.PaymentCreatedValue.Builder setPaymentId(long value) {
      validate(fields()[1], value);
      this.payment_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_id' field has been set.
      * @return True if the 'payment_id' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'payment_id' field.
      * @return This builder.
      */
    public com.example.payment.PaymentCreatedValue.Builder clearPaymentId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.example.payment.PaymentCreatedValue.Builder setType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.example.payment.PaymentCreatedValue.Builder clearType() {
      type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentCreatedValue build() {
      try {
        PaymentCreatedValue record = new PaymentCreatedValue();
        record.request_id = fieldSetFlags()[0] ? this.request_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.payment_id = fieldSetFlags()[1] ? this.payment_id : (java.lang.Long) defaultValue(fields()[1]);
        record.type = fieldSetFlags()[2] ? this.type : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentCreatedValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentCreatedValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentCreatedValue>
    READER$ = (org.apache.avro.io.DatumReader<PaymentCreatedValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
