/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.shipment;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ShipmentCreatedValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7464326671698762669L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShipmentCreatedValue\",\"namespace\":\"com.example.shipment\",\"fields\":[{\"name\":\"request_id\",\"type\":\"string\"},{\"name\":\"order_id\",\"type\":\"long\"},{\"name\":\"item\",\"type\":\"string\"},{\"name\":\"payment_type\",\"type\":\"string\"},{\"name\":\"courier\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShipmentCreatedValue> ENCODER =
      new BinaryMessageEncoder<ShipmentCreatedValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShipmentCreatedValue> DECODER =
      new BinaryMessageDecoder<ShipmentCreatedValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ShipmentCreatedValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ShipmentCreatedValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ShipmentCreatedValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ShipmentCreatedValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ShipmentCreatedValue from a ByteBuffer. */
  public static ShipmentCreatedValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence request_id;
  @Deprecated public long order_id;
  @Deprecated public java.lang.CharSequence item;
  @Deprecated public java.lang.CharSequence payment_type;
  @Deprecated public java.lang.CharSequence courier;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShipmentCreatedValue() {}

  /**
   * All-args constructor.
   * @param request_id The new value for request_id
   * @param order_id The new value for order_id
   * @param item The new value for item
   * @param payment_type The new value for payment_type
   * @param courier The new value for courier
   */
  public ShipmentCreatedValue(java.lang.CharSequence request_id, java.lang.Long order_id, java.lang.CharSequence item, java.lang.CharSequence payment_type, java.lang.CharSequence courier) {
    this.request_id = request_id;
    this.order_id = order_id;
    this.item = item;
    this.payment_type = payment_type;
    this.courier = courier;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return request_id;
    case 1: return order_id;
    case 2: return item;
    case 3: return payment_type;
    case 4: return courier;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: request_id = (java.lang.CharSequence)value$; break;
    case 1: order_id = (java.lang.Long)value$; break;
    case 2: item = (java.lang.CharSequence)value$; break;
    case 3: payment_type = (java.lang.CharSequence)value$; break;
    case 4: courier = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'request_id' field.
   * @return The value of the 'request_id' field.
   */
  public java.lang.CharSequence getRequestId() {
    return request_id;
  }

  /**
   * Sets the value of the 'request_id' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.CharSequence value) {
    this.request_id = value;
  }

  /**
   * Gets the value of the 'order_id' field.
   * @return The value of the 'order_id' field.
   */
  public java.lang.Long getOrderId() {
    return order_id;
  }

  /**
   * Sets the value of the 'order_id' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.Long value) {
    this.order_id = value;
  }

  /**
   * Gets the value of the 'item' field.
   * @return The value of the 'item' field.
   */
  public java.lang.CharSequence getItem() {
    return item;
  }

  /**
   * Sets the value of the 'item' field.
   * @param value the value to set.
   */
  public void setItem(java.lang.CharSequence value) {
    this.item = value;
  }

  /**
   * Gets the value of the 'payment_type' field.
   * @return The value of the 'payment_type' field.
   */
  public java.lang.CharSequence getPaymentType() {
    return payment_type;
  }

  /**
   * Sets the value of the 'payment_type' field.
   * @param value the value to set.
   */
  public void setPaymentType(java.lang.CharSequence value) {
    this.payment_type = value;
  }

  /**
   * Gets the value of the 'courier' field.
   * @return The value of the 'courier' field.
   */
  public java.lang.CharSequence getCourier() {
    return courier;
  }

  /**
   * Sets the value of the 'courier' field.
   * @param value the value to set.
   */
  public void setCourier(java.lang.CharSequence value) {
    this.courier = value;
  }

  /**
   * Creates a new ShipmentCreatedValue RecordBuilder.
   * @return A new ShipmentCreatedValue RecordBuilder
   */
  public static com.example.shipment.ShipmentCreatedValue.Builder newBuilder() {
    return new com.example.shipment.ShipmentCreatedValue.Builder();
  }

  /**
   * Creates a new ShipmentCreatedValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShipmentCreatedValue RecordBuilder
   */
  public static com.example.shipment.ShipmentCreatedValue.Builder newBuilder(com.example.shipment.ShipmentCreatedValue.Builder other) {
    return new com.example.shipment.ShipmentCreatedValue.Builder(other);
  }

  /**
   * Creates a new ShipmentCreatedValue RecordBuilder by copying an existing ShipmentCreatedValue instance.
   * @param other The existing instance to copy.
   * @return A new ShipmentCreatedValue RecordBuilder
   */
  public static com.example.shipment.ShipmentCreatedValue.Builder newBuilder(com.example.shipment.ShipmentCreatedValue other) {
    return new com.example.shipment.ShipmentCreatedValue.Builder(other);
  }

  /**
   * RecordBuilder for ShipmentCreatedValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShipmentCreatedValue>
    implements org.apache.avro.data.RecordBuilder<ShipmentCreatedValue> {

    private java.lang.CharSequence request_id;
    private long order_id;
    private java.lang.CharSequence item;
    private java.lang.CharSequence payment_type;
    private java.lang.CharSequence courier;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.shipment.ShipmentCreatedValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.request_id)) {
        this.request_id = data().deepCopy(fields()[0].schema(), other.request_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order_id)) {
        this.order_id = data().deepCopy(fields()[1].schema(), other.order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.item)) {
        this.item = data().deepCopy(fields()[2].schema(), other.item);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.payment_type)) {
        this.payment_type = data().deepCopy(fields()[3].schema(), other.payment_type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.courier)) {
        this.courier = data().deepCopy(fields()[4].schema(), other.courier);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ShipmentCreatedValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.shipment.ShipmentCreatedValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.request_id)) {
        this.request_id = data().deepCopy(fields()[0].schema(), other.request_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order_id)) {
        this.order_id = data().deepCopy(fields()[1].schema(), other.order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.item)) {
        this.item = data().deepCopy(fields()[2].schema(), other.item);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.payment_type)) {
        this.payment_type = data().deepCopy(fields()[3].schema(), other.payment_type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.courier)) {
        this.courier = data().deepCopy(fields()[4].schema(), other.courier);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'request_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getRequestId() {
      return request_id;
    }

    /**
      * Sets the value of the 'request_id' field.
      * @param value The value of 'request_id'.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder setRequestId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.request_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'request_id' field has been set.
      * @return True if the 'request_id' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'request_id' field.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder clearRequestId() {
      request_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'order_id' field.
      * @return The value.
      */
    public java.lang.Long getOrderId() {
      return order_id;
    }

    /**
      * Sets the value of the 'order_id' field.
      * @param value The value of 'order_id'.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder setOrderId(long value) {
      validate(fields()[1], value);
      this.order_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'order_id' field has been set.
      * @return True if the 'order_id' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'order_id' field.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder clearOrderId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'item' field.
      * @return The value.
      */
    public java.lang.CharSequence getItem() {
      return item;
    }

    /**
      * Sets the value of the 'item' field.
      * @param value The value of 'item'.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder setItem(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.item = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'item' field has been set.
      * @return True if the 'item' field has been set, false otherwise.
      */
    public boolean hasItem() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'item' field.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder clearItem() {
      item = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'payment_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentType() {
      return payment_type;
    }

    /**
      * Sets the value of the 'payment_type' field.
      * @param value The value of 'payment_type'.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder setPaymentType(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.payment_type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'payment_type' field has been set.
      * @return True if the 'payment_type' field has been set, false otherwise.
      */
    public boolean hasPaymentType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'payment_type' field.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder clearPaymentType() {
      payment_type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'courier' field.
      * @return The value.
      */
    public java.lang.CharSequence getCourier() {
      return courier;
    }

    /**
      * Sets the value of the 'courier' field.
      * @param value The value of 'courier'.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder setCourier(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.courier = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'courier' field has been set.
      * @return True if the 'courier' field has been set, false otherwise.
      */
    public boolean hasCourier() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'courier' field.
      * @return This builder.
      */
    public com.example.shipment.ShipmentCreatedValue.Builder clearCourier() {
      courier = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShipmentCreatedValue build() {
      try {
        ShipmentCreatedValue record = new ShipmentCreatedValue();
        record.request_id = fieldSetFlags()[0] ? this.request_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.order_id = fieldSetFlags()[1] ? this.order_id : (java.lang.Long) defaultValue(fields()[1]);
        record.item = fieldSetFlags()[2] ? this.item : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.payment_type = fieldSetFlags()[3] ? this.payment_type : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.courier = fieldSetFlags()[4] ? this.courier : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShipmentCreatedValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShipmentCreatedValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShipmentCreatedValue>
    READER$ = (org.apache.avro.io.DatumReader<ShipmentCreatedValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
