camunda:
  bpm:
    generic-properties:
      properties:
        historyCleanupBatchWindowStartTime: "00:01"
        historyCleanupBatchWindowEndTime: "23:59"
        historyCleanupStrategy: endTimeBased
    jpa:
      enabled: true
spring:
  cloud:
    stream:
      bindings:
        orderCreatedSink:
          destination: order.created
          group: spring-cloud-stream-bpm
          consumer:
            useNativeDecoding: true
        orderCreatedSource:
          destination: order.created
          producer:
            useNativeEncoding: true
        paymentCreatedSink:
          destination: payment.created
          group: spring-cloud-stream-bpm
          consumer:
            useNativeDecoding: true
        paymentCreatedSource:
          destination: payment.created
          producer:
            useNativeEncoding: true
        shipmentCreatedSource:
          destination: shipment.created
          producer:
            useNativeEncoding: true
      kafka:
        binder:
          autoCreateTopics: true
          brokers: kafka:9092
          consumer-properties:
            auto.register.schemas: true
            schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
          producer-properties:
            auto.register.schemas: true
            schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        bindings:
          orderCreatedSink:
            consumer:
              configuration:
                key:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value:
                  deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
          orderCreatedSource:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
                value:
                  serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
          paymentCreatedSink:
            consumer:
              configuration:
                key:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value:
                  deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
          paymentCreatedSource:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
                value:
                  serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
          shipmentCreatedSource:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
                value:
                  serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
  datasource:
    url: jdbc:mysql://default:3306/kafka_test?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: voxloud
