spring:
  cloud:
    stream:
      bindings:
        input:
          destination: user
          group: hello
          consumer:
            useNativeDecoding: true
        output:
          destination: user
          producer:
            useNativeEncoding: true
      kafka:
        binder:
          autoCreateTopics: true
          brokers: kafka:9092
          consumer-properties:
            auto.register.schemas: true
            schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
          producer-properties:
            auto.register.schemas: true
            schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        bindings:
          input:
            consumer:
              configuration:
                key:
                  deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value:
                  deserializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroDeserializer
          output:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
                value:
                  serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer